version: "3.9"
networks:
  deploy-babadzaki-dev:
    driver: bridge
services:
  app: 
    container_name: babadzaki_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - deploy-babadzaki-dev
    depends_on:
      - mssqlserver_db
  mssqlserver_db:  
    env_file:
    container_name: mssqlserver
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
    - MSSQL_USER=sa
    - MSSQL_PASSWORD=sa
    - MSSQL_DB=BabadzakiDb
    - ACCEPT_EULA=y
    ports:
      - "5432:5432"
    networks:
      - deploy-babadzaki-dev
    volumes:
      - mssql-data:/var/lib/mssql/data
volumes:
  mssql-data: