// <auto-generated />
using System;
using Babadzaki.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Babadzaki.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230320095931_AddBackgroundField")]
    partial class AddBackgroundField
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Babadzaki.Models.Email", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Emails");
                });

            modelBuilder.Entity("Babadzaki.Models.SeasonCollection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("TotalTokensNum")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("SeasonCollections");
                });

            modelBuilder.Entity("Babadzaki.Models.Token", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Background")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SeasonCollectionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SeasonCollectionId");

                    b.ToTable("Tokens", t =>
                        {
                            t.HasTrigger("UpdateTotalTokensNumAfterUpdate");
                        });
                });

            modelBuilder.Entity("Babadzaki.Models.Token", b =>
                {
                    b.HasOne("Babadzaki.Models.SeasonCollection", "SeasonCollection")
                        .WithMany("Tokens")
                        .HasForeignKey("SeasonCollectionId");

                    b.Navigation("SeasonCollection");
                });

            modelBuilder.Entity("Babadzaki.Models.SeasonCollection", b =>
                {
                    b.Navigation("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
