// <auto-generated />
using System;
using Babadzaki.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Babadzaki.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230320143805_AddAttributesAndFilters")]
    partial class AddAttributesAndFilters
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Babadzaki.Models.Attribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FilterId")
                        .HasColumnType("int");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FilterId");

                    b.ToTable("Attribute");
                });

            modelBuilder.Entity("Babadzaki.Models.Email", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Emails");
                });

            modelBuilder.Entity("Babadzaki.Models.Filter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsChecked")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Filter");
                });

            modelBuilder.Entity("Babadzaki.Models.SeasonCollection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("TotalTokensNum")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("SeasonCollections");
                });

            modelBuilder.Entity("Babadzaki.Models.Token", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SeasonCollectionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SeasonCollectionId");

                    b.ToTable("Tokens", t =>
                        {
                            t.HasTrigger("UpdateTotalTokensNumAfterUpdate");
                        });
                });

            modelBuilder.Entity("Babadzaki.Models.TokensAttributes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttributeId")
                        .HasColumnType("int");

                    b.Property<int>("SeasonCollectionId")
                        .HasColumnType("int");

                    b.Property<int>("TokenId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AttributeId");

                    b.HasIndex("SeasonCollectionId");

                    b.ToTable("TokensAttributes");
                });

            modelBuilder.Entity("Babadzaki.Models.Attribute", b =>
                {
                    b.HasOne("Babadzaki.Models.Filter", "Filter")
                        .WithMany("Attributes")
                        .HasForeignKey("FilterId");

                    b.Navigation("Filter");
                });

            modelBuilder.Entity("Babadzaki.Models.Token", b =>
                {
                    b.HasOne("Babadzaki.Models.SeasonCollection", "SeasonCollection")
                        .WithMany("Tokens")
                        .HasForeignKey("SeasonCollectionId");

                    b.Navigation("SeasonCollection");
                });

            modelBuilder.Entity("Babadzaki.Models.TokensAttributes", b =>
                {
                    b.HasOne("Babadzaki.Models.Attribute", "Attribute")
                        .WithMany("TokensAttributes")
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Babadzaki.Models.Token", "Token")
                        .WithMany("TokensAttributes")
                        .HasForeignKey("SeasonCollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attribute");

                    b.Navigation("Token");
                });

            modelBuilder.Entity("Babadzaki.Models.Attribute", b =>
                {
                    b.Navigation("TokensAttributes");
                });

            modelBuilder.Entity("Babadzaki.Models.Filter", b =>
                {
                    b.Navigation("Attributes");
                });

            modelBuilder.Entity("Babadzaki.Models.SeasonCollection", b =>
                {
                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("Babadzaki.Models.Token", b =>
                {
                    b.Navigation("TokensAttributes");
                });
#pragma warning restore 612, 618
        }
    }
}
